---
apiVersion: v1
kind: Service
metadata:
  name: { { include "lxp-course-topic-service.fullname" . } }
  labels: { { - include "lxp-course-topic-service.labels" . | nindent 4 } }
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: 8080-tcp
  selector:
    { { - include "lxp-course-topic-service.selectorLabels" . | nindent 4 } }
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
