# Generated by Django 3.0.8 on 2020-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_topic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopicmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
